### PR TITLE
Fixed FIXMEs in Windows tests

### LINKED ISSUE #81: Resolve FIXMEs in test/Windows.hs

### PR DESCRIPTION
**Pull request by rkoeninger**
Fixes #81

In this PR:
* Added path separator de-duplication when normalizing paths on Windows, and at the tail of the drive.
  * On Posix, it still de-dupes consecutive slashes at the beginning of the path as before.
* Added check in `parseRelDir` that path is not all path separators (that's an absolute path on Posix and Windows).
* Removed test that asserted success when parsing `~/` on Windows as that's not a Windows thing.
* Changed a couple of relative dir path examples from successful to failing for paths that start with separators as that makes them absolute paths.
* Added handling of UNC (`\\host\share`) and Unicode (`\\?\C:\`) paths on Windows and tests for these types of paths

### CODE REVIEW

File: src/Path/Include.hs [hunk 1]
```diff
@@ -735,19 +740,41 @@ normalizeDir =
...
+normalizeLeadingSeps (p0:p1:ps) |
+  FilePath.isPathSeparator p0 && FilePath.isPathSeparator p1 =
+    normalizeLeadingSeps (FilePath.pathSeparator:ps)
+normalizeLeadingSeps path = path
+
+-- | Normalizes seps only at the end of a path.
+normalizeTrailingSeps :: FilePath -> FilePath
+normalizeTrailingSeps = reverse . normalizeLeadingSeps . reverse
+
+-- | Applies file system-specific sep normalization following @FilePath.normalise@.
```
Comment (sjakobi) [inline src/Path/Include.hs]: Dito regarding "file system-specific".

File: src/Path/Include.hs [hunk 2]
```diff
@@ -735,19 +740,41 @@ normalizeDir =
...
-  | IS_WINDOWS = FilePath.normalise
-  | otherwise = normalizeLeadingSeparators . FilePath.normalise
-    where
-        sep = FilePath.pathSeparator
-        normalizeLeadingSeparators (x1:x2:xs) | x1 == sep && x2 == sep
-            = normalizeLeadingSeparators (sep:xs)
-        normalizeLeadingSeparators x = x
-#endif
+  | IS_WINDOWS = normalizeSepsExceptLeading . FilePath.normalise
+  | otherwise  = normalizeLeadingSeps . FilePath.normalise
```
Comment (sjakobi) [inline src/Path/Include.hs]: I think we should try to get these extra normalizations upstreamed into `filepath`. As you already appear to be quite familiar with this topic, maybe you'd like to give this a try @rkoeninger?!

File: test/Windows.hs [hunk 3]
```diff
@@ -231,13 +239,19 @@ parseAbsFileSpec =
...
+     failing "\\..."
+     failing "\\foo.txt"
+     succeeding "C:\\\\\\foo\\\\bar\\\\\\\\mu.txt" (Path "C:\\foo\\bar\\mu.txt")
+     succeeding "C:\\\\\\foo\\\\bar\\.\\\\mu.txt" (Path "C:\\foo\\bar\\mu.txt")
+     succeeding "\\\\unchost\\share\\\\file.txt" (Path "\\\\unchost\\share\\file.txt")
+     succeeding "\\/unchost\\share\\\\file.txt" (Path "\\\\unchost\\share\\file.txt")
+     succeeding "\\\\unchost\\share\\.\\folder\\\\\\file.txt" (Path "\\\\unchost\\share\\folder\\file.txt")
+     succeeding "\\\\?\\C:\\file.txt" (Path "\\\\?\\C:\\file.txt")
+     succeeding "/\\?\\C:\\file.txt" (Path "\\\\?\\C:\\file.txt")
+     succeeding "\\\\?\\C:\\\\\\folder\\.\\\\file.txt" (Path "\\\\?\\C:\\folder\\file.txt")
```
Comment (sjakobi) [inline test/Windows.hs]: `filepath` says something about some of these not being relative paths: http://hackage.haskell.org/package/filepath-1.4.2.1/docs/System-FilePath-Windows.html#v:isRelative

Can you check?

If these in fact _are_ valid relative paths, can we correctly append them with `</>`?

Comment (rkoeninger) [reply test/Windows.hs]: That's under `parseAbsFileSpec`, so we're testing that they're valid absolute paths on these lines.

Under `parseRelFileSpec`, there are tests that these patterns fail.

Comment (sjakobi) [reply test/Windows.hs]: > That's under parseAbsFileSpec, so we're testing that they're valid absolute paths on these lines.

Oops, my bad.

> I'll look at adding tests for </>.

:+1:

File: src/Path/Include.hs [hunk 4]
```diff
@@ -735,19 +740,41 @@ normalizeDir =
...
+normalizeSepsExceptLeading path = normLeadingSeps ++ normalizeAllSeps rest
+  where leadingSeps = takeWhile FilePath.isPathSeparator path
+        normLeadingSeps = replicate (min 2 (length leadingSeps)) FilePath.pathSeparator
+        rest = dropWhile FilePath.isPathSeparator path
+
+-- | Normalizes seps only at the beginning of a path.
+normalizeLeadingSeps :: FilePath -> FilePath
+normalizeLeadingSeps (p0:p1:ps) |
+  FilePath.isPathSeparator p0 && FilePath.isPathSeparator p1 =
+    normalizeLeadingSeps (FilePath.pathSeparator:ps)
```
[the remark this answers is not in the document]
Comment (rkoeninger) [reply src/Path/Include.hs]: Done here and in `normalizeSepsExceptLeading`, making that one cleaner, too.

File: src/Path/Include.hs (hunk 2 above)
Comment (rkoeninger) [reply src/Path/Include.hs]: You're suggesting I open an issue on https://github.com/haskell/filepath after this is merged? And if `filepath` gets released with these normalization functions, we'll come back and remove them from this library?

**Comment by rkoeninger** [comment]
@sjakobi Added several Windows-specific tests for UNC and Unicode paths for `</>`, `stripProperPrefix`, `isProperPrefix`, `filename`, `dirname` and `parent`. Added notes to changelog.

File: test/Windows.hs (hunk 3 above)
Comment (rkoeninger) [reply test/Windows.hs]: Tests added

File: src/Path/Include.hs [hunk 5]
```diff
@@ -723,31 +728,48 @@ mkRelFile = either (error . show) lift . parseRelFile
...
+        normSeps ch path@(p0:_)
+          | FilePath.isPathSeparator ch && FilePath.isPathSeparator p0 = path
+          | FilePath.isPathSeparator ch = FilePath.pathSeparator:path
+          | otherwise = ch:path
+
+-- | Normalizes seps except at the beginning of path.
+normalizeSepsExceptLeading :: FilePath -> FilePath
+normalizeSepsExceptLeading path = normLeadingSeps ++ normalizeAllSeps rest
+  where (leadingSeps, rest) = span FilePath.isPathSeparator path
+        normLeadingSeps = replicate (min 2 (length leadingSeps)) FilePath.pathSeparator
```
Comment (sjakobi) [inline src/Path/Include.hs]: Given that we in fact do some leading path sep normalization, I guess this function deserves a better name and more correct documentation. How about `normalizeSepsWin` for example? That would also make it clear that it's Windows-specific.

File: test/Windows.hs [hunk 6]
```diff
@@ -58,35 +59,51 @@ restrictions =
...
-    (dirname $(mkRelDir ".") == $(mkRelDir "."))
-  it
-    "dirname C:\\ must be a Rel path"
-    ((parseAbsDir $ show $ dirname (fromJust (parseAbsDir "C:\\"))
-     :: Maybe (Path Abs Dir)) == Nothing)
+operationDirname =
+  do it "dirname ($(mkAbsDir parent) </> $(mkRelFile dirname)) == dirname $(mkRelFile dirname) (absolute)"
+        (dirnamesShouldBeEqual
+          ($(mkAbsDir "C:\\chris\\") </> $(mkRelDir "bar"))
+           $(mkRelDir "bar"))
```
Comment (sjakobi) [inline test/Windows.hs]: To me, the additional indentation of the second argument to `dirnamesShouldBeEqual` suggests that it is inside the parentheses opened in the line above. But it's not an important issue, you don't have to change it.

File: test/Windows.hs [hunk 7]
```diff
@@ -110,66 +127,102 @@ operationIsProperPrefixOf =
...
-        (stripProperPrefix $(mkRelDir "bar\\")
-                  ($(mkRelDir "bar\\") </>
-                   $(mkRelFile "bob\\foo.txt")) ==
-         Just $(mkRelFile "bob\\foo.txt"))
-
+  do it "stripProperPrefix parent (parent </> child) = child (absolute)"
+        (remainingPathShouldBe
+          $(mkAbsDir "C:\\\\\\bar\\")
+         ($(mkAbsDir "C:\\\\\\bar\\") </> $(mkRelFile "bar\\foo.txt"))
+         (Just $(mkRelFile "bar\\foo.txt")))
```
Comment (sjakobi) [inline test/Windows.hs]: The decreasing indentation here is more confusing IMHO.

File: src/Path/Include.hs (hunk 2 above)
Comment (sjakobi) [reply src/Path/Include.hs]: > I can open an issue on https://github.com/haskell/filepath ?

That would be great! :)

> We'll come back and clear out the normalization functions once they're released in upstream.

I think we want to keep compatibility with the `filepath` versions from the last ~3 years. But eventually we should be able to delete most of our normalization code.

File: src/Path/Include.hs (hunk 5 above)
Comment (rkoeninger) [reply src/Path/Include.hs]: Renamed to `normalizeWindowsSeps` and expanded comment.

I wanted those internal functions to be more reusable, but yeah that one is too specific.

**Comment by rkoeninger** [comment]
@sjakobi Made suggested changes.
